# The deployment for the Collector pod.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubecostcollector
  name: kubecostcollector
  namespace: costapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecostcollector
  template:
    metadata:
      labels:
        app: kubecostcollector
      name: kubecostcollector
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EKS_CLUSTER_NAME
          value: "your-eks-cluster-name"
        image: <dockerhub-account>/pod-resource-collector:latest
        imagePullPolicy: Always
        name: kubecostcollector
        command: ["/usr/local/bin/python3"]
        args: ["-u", "/app/pod_resource_collector.py"]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccountName: costapp-collector
---
apiVersion: v1
kind: Service
metadata:
  name: kubecostcollector
  namespace: costapp
  labels:
    app: kubecostcollector
spec:
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
  selector:
    app: kubecostcollector
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubecostcollector
  namespace: costapp
  labels:
    app: kubecostcollector
spec:
  selector:
    matchLabels:
      app: kubecostcollector
  endpoints:
    - port: http-metrics
      interval: 30s
